[package]
name = "client"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
api-boundary = { path="api-boundary" } 

leptos = { version = "0.5.4" }
leptos_router = { version = "0.5.4", features = ["csr"] }
web-sys = "0.3.66"
async-std = "1.12.0"
lazy_static = "1.4.0"
log = "0.4"
console_error_panic_hook = "0.1"
console_log = "1.0"
gloo-net = "0.5"
gloo-storage = "0.3"
serde = "1.0"
thiserror = "1.0"



